= Kafka Docker Image - in progress

== Setup

* Setup (currently only tested on a Mac) -
** in vBox or vmWare Fusion, create an Ubuntu Server 16 VM
** for networking, use 'Share with my Mac' where the Mac serves as a NAT gateway for the VM
** log in to that VM from your Mac's terminal `ssh user@<VM_EXTERNAL_IP>`
** install docker-engine on that VM using the instructions from the Docker website
** clone this repo into that virtual machine.
** from that machine, run `ifconfig` and note the `ens33` network interface, which should be the externally-accessible ip address.
From here on, that IP will be referred to as `$EXT_IP`

== Building
----
cd <project root>
sudo docker build -t rhardt/simple-docker-kafka .
----

== Running
* From your ssh session into the VM:
----
EXT_IP=<your vm external ip>
sudo docker run -p 2181:2181 -p 9092:9092 -e KAFKA_ADVERTISED_HOST_NAME=$EXT_IP -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://$EXT_IP:9092 -e KAFKA_CREATE_TOPICS=topic1:3:1,topic2:4:1,topic3:2:1 -e KAFKA_ZOOKEEPER_CONNECT=$EXT_IP:2181 rhardt/simple-docker-kafka

----
** at this point it should be running.  Now we test.

== Testing
* download
** From another terminal window on your mac...
** download the _2.11-0.10.0.0_ version of kafka.  The exact version is _very important_.
** unzip and navigate to $KAFKA/bin
** `$EXT_IP=<your vm external ip>`
** `./kafka-topics.sh --create --topic testtopic --zookeeper $EXT_IP:2181 --partitions 4 --replication-factor 1`
** verify the topic with `./kafka-topics.sh --list --zookeeper $EXT_IP:2181` - you should see the topic you just created
** put some messages on the topic
----
./kafka-console-producer.sh --broker-list $EXT_IP:9092 --topic topic1
----
** type a few words separated with a `<return>` or newline
** <ctrl>-c to exit
** now we'll read the messages off the topic
----
./kafka-console-consumer.sh --zookeeper $EXT_IP:2181 --topic topic1 --from-beginning
----
** you should see your words from the previous step, though not in any particular order

== TROUBLESHOOTING
* you can open a bash shell into the container and look at the contents of /var/log/supervisord for detailed logs from Kafka and Zookeeper

== TODO:

* buy a beer for the creators of `https://github.com/wurstmeister/kafka-docker` from whom we shamelessly exfiltrated some amazing shell scripts.

* use docker-compose to set up multi-node clusters

* docker-bosh!











